# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"   # backward compatibility
spec:
  ingressClassName: nginx                  # explicitly tell K8s to use nginx ingress controller
  rules:
  - host: go-web-app.local                 # replace with your domain or ELB CNAME later
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-web-app
            port:
              number: 80


